### ISSUE TITLE
'TLSClientKeyExchange' and 'TLSClientECDHParams'

### ISSUE THREAD

**Issue by fbessez** [tintinweb/scapy-ssl_tls#108]
Hi, 

I am getting the following error: `Traceback (most recent call last):
  File "client_hello_with_session_ticket.py", line 38, in <module>
    tls_ctx.get_client_kex_data()])
  File "/media/sf_TLS_Tutorial/scapy-ssl_tls/scapy_ssl_tls/ssl_tls_crypto.py", line 577, in get_client_kex_data
    return tls.TLSClientKeyExchange() / tls.TLSClientECDHParams(data=self.get_client_ecdh_pubkey(val))
TypeError: unsupported operand type(s) for /: 'TLSClientKeyExchange' and 'TLSClientECDHParams'
'`

when running the following code: `

    if len(sys.argv) > 2:
        server = (sys.argv[1], int(sys.argv[2]))
    else:
        server = ("127.0.0.1", 8443)

    host = (sys.argv[1], int(sys.argv[2]))
    version = TLSVersion.TLS_1_2
    cipher = TLSCipherSuite.ECDHE_RSA_WITH_AES_256_CBC_SHA
    ticket = ""
    master_secret = ""

    with TLSSocket(socket.socket(), client=True) as tls_socket:
        tls_socket.connect(host)
        tls_ctx = tls_socket.tls_ctx

        pkt = TLSRecord() / \
            TLSHandshakes(handshakes=[TLSHandshake() /
                                      TLSClientHello(version=version,
                                                     cipher_suites=[cipher],
                                                     extensions=[TLSExtension() /
                                                                 TLSExtSessionTicketTLS(data="")])])

        # pkt.show()
        tls_socket.sendall(pkt)
        resp = tls_socket.recvall()
        # resp.show()
        client_key_exchange = TLSRecord(version=version) / \
                              TLSHandshakes(handshakes=[TLSHandshake() /
                                                        tls_ctx.get_client_kex_data()])
        # client_key_exchange.show()

        client_ccs = TLSRecord(version=version) / TLSChangeCipherSpec()
        tls_socket.sendall(TLS.from_records([client_key_exchange, client_ccs]))
        tls_socket.sendall(TLSHandshakes(handshakes=[TLSHandshake() /
                                                     TLSFinished(data=tls_socket.tls_ctx.get_verify_data())]))
        server_finished = tls_socket.recvall()
        # server_finished.show()
        ticket = server_finished[TLSSessionTicket].ticket
        tls_socket.sendall(TLSPlaintext(data="GET / HTTP/1.1\r\nHOST: localhost\r\n\r\n"))
        resp = tls_socket.recvall()
        # resp.show()
        master_secret = tls_ctx.master_secret`

It is a very slight variation of your client_hello_with_ticket.py example. 
I am running python2.7, if that makes a difference.

Thank you

**Comment by fbessez** [comment]
I think what might help me is knowing what your development environment is like:

Do you mind telling me what the following are for you?

Operating System:
Python Version:
Scapy Version:
Scapy-ssl_tls Version:

and any other necessary dependencies?

Thank you1

**Comment by alexmgr** [comment]
Hi @fbessez,

I can't repro your issue. What stack are you speaking to?
I run `scapy-ssl_tls` from `master` on OSX or Linux, with python 2.7.13, and `scapy` 2.3.2

**Comment by tintinweb** [comment]
closing due to inactivity. please re-open and provide a fully working example including details about your environment if the problem still persists. 

cheers
