### ISSUE TITLE
tls_1_3-client.py - TLS_1_3 client example fails integration external tests

### ISSUE THREAD

**Issue by tintinweb** [tintinweb/scapy-ssl_tls#114]
integration test: tls_1_3-client.py is currently failing:

```# python examples/tls_1_3-client.py tls13.cloudflare.com 443
WARNING: No route found for IPv6 destination :: (no default route?)
###[ SSL/TLS ]###
  \records   \

TLS Session Context:
    negotiated.version: UNKNOWN
    negotiated.ciphersuite: UNKNOWN
    negotiated.key_exchange: None
    negotiated.encryption: None
    negotiated.mac: None
    negotiated.compression: 0
    negotiated.resumption: False
    encrypted_premaster_secret: None
    premaster_secret: None
    master_secret: None
    early_secrets: None
    handshake_secrets: None
    master_secrets: None
    resumption_secret: None

    Client TLS context:
        random: 'ZJ\xcd\xe9X\x94\xbb\x8b=\xf9n\x1a\xfb\xd7\x1aZ\xbe\x84#^\x98\xea\x06\x1d\x14P\x15?\x84!\xeaW'
        session id: ''
        shares:
            ECDH Keystore:
            curve: secp256r1
            size: 256
            public: (65784327905464346414202945536039495226631169475038061124155754132953411300665, 111358793915316823269442380408231802709386467896961374510920245456591311874104) on "secp256r1" => y^2 = x^3 + 115792089210356248762697446949407573530086143415290314195533631308867097853948x + 41058363725152142129326129780047268409114441015993725554835256314039467401291 (mod 115792089210356248762697446949407573530086143415290314195533631308867097853951)
            private: 38277140221663347036400194175171131568162567488489668401868155075649733424459
        finished:
            secret: None
            finished hashes:
        Empty Asymmetrical Keystore:
            certificate: None
            size: 0
            public: None
            private: None
        <scapy_ssl_tls.ssl_tls_keystore.EmptyKexKeystore object at 0x98850ac>
        <scapy_ssl_tls.ssl_tls_keystore.EmptySymKeyStore object at 0x988516c>
        symetric keystore history:


    Server TLS context:
        random: None
        session id: None
        shares:

        finished:
            secret: None
            finished hashes:
        Empty Asymmetrical Keystore:
            certificate: None
            size: 0
            public: None
            private: None
        <scapy_ssl_tls.ssl_tls_keystore.EmptyKexKeystore object at 0x988552c>
        <scapy_ssl_tls.ssl_tls_keystore.EmptySymKeyStore object at 0x988556c>
        symetric keystore history:

Traceback (most recent call last):
  File "examples/tls_1_3-client.py", line 58, in <module>
    sys.exit(main())
  File "examples/tls_1_3-client.py", line 46, in main
    r = tls_socket.do_round_trip(TLSHandshakes(handshakes=[TLSHandshake() / TLSFinished(data=tls_socket.tls_ctx.get_verify_data())]), recv=False)
  File "/usr/local/lib/python2.7/dist-packages/scapy_ssl_tls/ssl_tls_crypto.py", line 600, in get_verify_data
    prf_verify_data = self.prf.get_bytes(self.master_secret, label,
AttributeError: 'NoneType' object has no attribute 'get_bytes'
```

example was introduced with: c76c2a65d313fc3c108c86c3941fe0a4990ae00a
cmd: `python examples/tls_1_3-client.py tls13.cloudflare.com 443`
scapy-ssl_tls checkout of c76c2a65d313fc3c108c86c3941fe0a4990ae00a also fails with same error against cloudflare.

verified tls13.cloudflare.com negotiates tls1.3-draft with chrome (requires manual step to enable it)

@alexmgr do we want to fix this before releasing the 2.0 (current master)?

**Comment by alexmgr** [comment]
Hey @tintinweb,

Didn't look into this, might be negotiating another draft version then what we have (18). Don't have much time right now, might disable the test?

**Comment by higher75** [comment]
Hey man, I also found this error recently. Can you tell me how to solve it
