### ISSUE TITLE
Installed pycrypto but can't import scapy-ssl_tls

### ISSUE THREAD

**Issue by confshared** [tintinweb/scapy-ssl_tls#123]
NOTE: `>>> from scapy_ssl_tls import * ` works but `>>> from scapy_ssl_tls.ssl_tls import TLS` does not.
I previously raised an issue and you advised me to install pycrypto. I did so:
```
C:\WINDOWS\system32>python -m pip install pycrypto
Collecting pycrypto
  Using cached pycrypto-2.6.1.tar.gz
Building wheels for collected packages: pycrypto
  Running setup.py bdist_wheel for pycrypto ... done
  Stored in directory: C:\myuser\e\AppData\Local\pip\Cache\wheels\80\1f\94\f76e9746864f198eb0e304aeec319159fa41b082f61281ffce
Successfully built pycrypto
Installing collected packages: pycrypto
Successfully installed pycrypto-2.6.1
```
I installed scapy:
```
C:\myuser\e\Documents\dev\tls\scapy-ssl_tls-master\scapy-ssl_tls-master>python setup.py install
WARNING: Found PyCrypto to be installed in your environment.
         Please note that the PyCrypto project seems to be in an unmaintaned state with known security issues. Consider switching to other alternatives. Ref: https://github.com/tintinweb/scapy-ssl_tls/pull/82#issuecomment-260004605
INFO: Installing scapy-ssl_tls layers to: ['C:\\Python27\\scapy-master\\scapy-master\\scapy', 'C:\\Python27\\lib\\site-packages\\scapy']
running install
running build
running build_py
running install_lib
running install_data
running install_egg_info
running egg_info
writing requirements to scapy_ssl_tls.egg-info\requires.txt
writing scapy_ssl_tls.egg-info\PKG-INFO
writing top-level names to scapy_ssl_tls.egg-info\top_level.txt
writing dependency_links to scapy_ssl_tls.egg-info\dependency_links.txt
reading manifest file 'scapy_ssl_tls.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'scapy_ssl_tls.egg-info\SOURCES.txt'
removing 'C:\Python27\Lib\site-packages\scapy_ssl_tls-1.3.0-py2.7.egg-info' (and everything under it)
Copying scapy_ssl_tls.egg-info to C:\Python27\Lib\site-packages\scapy_ssl_tls-1.3.0-py2.7.egg-info
running install_scripts
running post install task
INFO: Installing scapy-ssl_tls layers to: ['C:\\Python27\\scapy-master\\scapy-master\\scapy', 'C:\\Python27\\lib\\site-packages\\scapy']
```
When I try to import it in python, this is what I get:
```
C:\myuser\e\Documents\dev\tls\scapy-ssl_tls-master\scapy-ssl_tls-master>python
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy_ssl_tls.ssl_tls import TLS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "scapy_ssl_tls\ssl_tls.py", line 7, in <module>
    from scapy.layers.inet import TCP, UDP
  File "C:\Python27\lib\site-packages\scapy\layers\inet.py", line 14, in <module>
    from scapy.layers.l2 import *
  File "C:\Python27\lib\site-packages\scapy\layers\l2.py", line 14, in <module>
    from scapy.ansmachine import *
  File "C:\Python27\lib\site-packages\scapy\ansmachine.py", line 14, in <module>
    from sendrecv import send,sendp,sniff
  File "C:\Python27\lib\site-packages\scapy\sendrecv.py", line 13, in <module>
    import arch
  File "C:\Python27\lib\site-packages\scapy\arch\__init__.py", line 80, in <module>
    from windows import *
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 17, in <module>
    from scapy.sendrecv import debug, srp1
ImportError: cannot import name debug
>>> from pycrypto import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pycrypto
```

**Comment by tintinweb** [comment]
Hi @confshared,

please stick the general code of conduct and do not duplicate your own tickets, stick to one ticket/issue per topic and add your notes as comments to this ticket otherwise this will become unmanagable. (see #121 and linked tickets)

Please consult the pycrypto documentation as this is not a problem specific to scapy/scapy_ssl_tls. Even though the package might be called `pycrypto` the import modules name might be different.

-->https://pypi.python.org/pypi/pycrypto
```
>>> from Crypto.Hash import SHA256
>>> hash = SHA256.new()```

**Comment by confshared** [comment]
Pycrypto is installed successfully:
```
C:\Users\e\Documents\dev\tls\testing\>python -m pip install pycrypto
Requirement already satisfied: pycrypto in c:\python27\lib\site-packages
```
And tested:
```
>>> from Crypto.Hash import SHA256
>>>

The problem is not that pycrypto is not installed.
```
