### ISSUE TITLE
How to create the Certificate Status message from the server? Any examples would be appreciated.

### ISSUE THREAD

**Issue by pratikmohanty** [tintinweb/scapy-ssl_tls#154]
I tried the following:-
dn1 = x509.X509_ExtDefault(binascii.unhexlify('310b300906035504061302494e'))
                        dn2 = x509.X509_ExtDefault(binascii.unhexlify('310c300a060355040813034b4152'))
                        dn3 = x509.X509_ExtDefault(binascii.unhexlify('311b3019060355040a14124369747269782052264420507674204c7464'))
                        dn4 = x509.X509_ExtDefault(binascii.unhexlify('310f300d06035504031306436974726978'))
                        certificate_request = TLSCertificateRequest(algs=0x0401, ca_dns =TLSCADistinguishedName(ca_dn=dn1 / dn2 / dn3 / dn4))
                        cert_req_record = TLSRecord(version=version) / TLSHandshakes(handshakes=[ TLSHandshake() / certificate_request])
                        cert_req_record.show()
                        client_socket.sendall(cert_req_record)

But it throws an error at sendall as below:-

Traceback (most recent call last):
  File "server_rsa_cert_multiple_records_cr.py", line 99, in <module>
    main()
  File "server_rsa_cert_multiple_records_cr.py", line 78, in main
    client_socket.sendall(cert_req_record)
  File "/usr/local/lib/python2.7/dist-packages/scapy_ssl_tls/ssl_tls.py", line 1394, in sendall
    self._s.sendall(str(pkt))
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 343, in __str__
    return str(self.build())
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 444, in build
    p = self.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy_ssl_tls/ssl_tls.py", line 461, in do_build
    if len(self.payload) > TLSRecord.MAX_LEN:

The Certificate Request message is properly formed as shown below:-
###[ TLS Handshakes ]###
     \handshakes\
      |###[ TLS Handshake ]###
      |  type      = certificate_request
      |  length    = None
      |###[ TLS Certificate Request ]###
      |     type_length= None
      |     \types     \
      |      |###[ TLS Certificate Type ]###
      |      |  type      = rsa_sign
      |     alg_length= None
      |     algs      = ['rsa_pkcs1_sha256']
      |     dn_length = None
      |     \ca_dns    \
      |      |###[ TLS CA Distinguished Name ]###
      |      |  length    = None
      |      |  \ca_dn     \
      |      |   |###[ X509_ExtDefault ]###
      |      |   |  value     = <ASN1_SET[[<ASN1_SEQUENCE[[<ASN1_OID['countryName']>, <ASN1_PRINTABLE_STRING['IN']>]]>]]>
      |      |   |###[ X509_ExtDefault ]###
      |      |   |     value     = <ASN1_SET[[<ASN1_SEQUENCE[[<ASN1_OID['stateOrProvinceName']>, <ASN1_PRINTABLE_STRING['KAR']>]]>]]>
      |      |   |###[ X509_ExtDefault ]###
      |      |   |        value     = <ASN1_SET[[<ASN1_SEQUENCE[[<ASN1_OID['organizationName']>, <ASN1_T61_STRING['Citrix R&D Pvt Ltd']>]]>]]>
      |      |   |###[ X509_ExtDefault ]###
      |      |   |           value     = <ASN1_SET[[<ASN1_SEQUENCE[[<ASN1_OID['commonName']>, <ASN1_PRINTABLE_STRING['Citrix']>]]>]]>

**Comment by pratikmohanty** [comment]
Got it to work using the below:-
dn_header = binascii.unhexlify('004b3049')
                        dn1 = x509.X509_ExtDefault(binascii.unhexlify('310b300906035504061302494e'))
                        dn2 = x509.X509_ExtDefault(binascii.unhexlify('310c300a060355040813034b4152'))
                        dn3 = x509.X509_ExtDefault(binascii.unhexlify('311b3019060355040a14124369747269782052264420507674204c7464'))
                        dn4 = x509.X509_ExtDefault(binascii.unhexlify('310f300d06035504031306436974726978'))
                        certificate_request = TLSCertificateRequest(algs=0x0401,ca_dns=dn_header/ dn1 / dn2 / dn3 / dn4,dn_length=77)
                        cert_req_record = TLSRecord(version=version) / TLSHandshakes(handshakes=[ TLSHandshake() / certificate_request])

dn1,dn2,dn3,dn4 are the different DNs for the CA certificate.
