### ISSUE TITLE
2.0.0 server_rsa.py quit with error

### ISSUE THREAD

**Issue by bigorc** [tintinweb/scapy-ssl_tls#155]
Traceback (most recent call last):
  File "server_rsa.py", line 71, in <module>
    main()
  File "server_rsa.py", line 59, in main
    TLSFinished(data=client_socket.tls_ctx.get_verify_data())]))
  File "/usr/local/lib/python2.7/dist-packages/scapy_ssl_tls/ssl_tls_crypto.py", line 643, in get_verify_data
    num_bytes=12)
  File "/usr/local/lib/python2.7/dist-packages/scapy_ssl_tls/ssl_tls_crypto.py", line 732, in get_bytes
    bytes_ = self._get_bytes(self.digest, key, label, random, num_bytes)
  File "/usr/local/lib/python2.7/dist-packages/scapy_ssl_tls/ssl_tls_crypto.py", line 751, in _get_bytes
    block = HMAC.new(key=key, msg="%s%s" % (label, random), digestmod=digest).digest()
  File "/usr/local/lib/python2.7/dist-packages/Cryptodome/Hash/HMAC.py", line 213, in new
    return HMAC(key, msg, digestmod)
  File "/usr/local/lib/python2.7/dist-packages/Cryptodome/Hash/HMAC.py", line 71, in __init__
    if len(key) <= digestmod.block_size:
TypeError: object of type 'NoneType' has no len()

**Comment by Seumi** [comment]
i have the same problem, have you solved this problem yet
