### ISSUE TITLE
Pip Install Error

### ISSUE THREAD

**Issue by hasanali586q** [tintinweb/scapy-ssl_tls#168]
help me pls

pip install scapy-ssl_tls

` Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\VeyselXan\AppData\Local\Temp\pip-install-0ppcuffu\scapy-ssl-tls_ff3c344cfc674cec87920c36a648f1ad\setup.py", line 31
          except AttributeError, ex:
                               ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by russdm** [comment]
Change the comma in the setup file to as.

**Comment by russdm** [comment]
It probably won't work after that, as there's another issue generating os permissions. chmod(0755,fname) if you can find the line with that command change it to chmod(0o755,fname) for octal format. Good luck!

**Comment by Frank-Buss** [comment]
I think this is a problem with Python 3, might still work with Python 2. But looks like this project is dead, any alternative?

**Comment by mohag** [comment]
> I think this is a problem with Python 3, might still work with Python 2. But looks like this project is dead, any alternative?

[The built-in support](https://scapy.readthedocs.io/en/latest/api/scapy.layers.tls.html)

It works, examples, etc are hard to find...
