### ISSUE TITLE
ssl_tls_crypto.py: hmac functions return error

### ISSUE THREAD

**Issue by abpabab** [tintinweb/scapy-ssl_tls#36]
Your sessionctx_sniffer.py examples python script, I got bellow errors when running:

---

Traceback (most recent call last):
  File "decode_on_the_fly.py", line 110, in <module>
    sniff(iface=conf.iface, filter="tcp port 443", prn=process_ssl, store=0, count=0)
  File "/usr/lib/python2.6/site-packages/scapy/sendrecv.py", line 559, in sniff
    r = prn(p)
  File "decode_on_the_fly.py", line 66, in process_ssl
    pp = to_raw(TLSPlaintext(),session)
  File "/usr/lib/python2.6/site-packages/scapy_ssl_tls/ssl_tls.py", line 811, in to_raw
    crypto_container = tlsc.CryptoContainer(tls_ctx, cleartext, content_type)
  File "/usr/lib/python2.6/site-packages/scapy_ssl_tls/ssl_tls_crypto.py", line 511, in __init__
    self.hmac()
  File "/usr/lib/python2.6/site-packages/scapy_ssl_tls/ssl_tls_crypto.py", line 520, in hmac
    len_ = struct.pack("!H", data_len or len(self.data))
TypeError: object of type 'NoneType' has no len()

---

I open that file set pdb.set_trace() to print self.data, it's always is "None" so this function always return error.

**Comment by tintinweb** [comment]
The sessionctx_sniffer is based on a pretty old codebase (pre v1.0) and was just not updated while progressing with the latest features therefore it is not compatible with the current version but we're already working on making it work for the next release.

**Comment by abpabab** [comment]
Dear tintin,

Your reply help me a lot. I got master_secret and it's enough to me now. I
will waiting for your next interesting sessionctx_sniffer.py.

Thank you so much.

Best regards,

--maximus
