### ISSUE TITLE
error for sniff with interface

### ISSUE THREAD

**Issue by gunvant3** [tintinweb/scapy-ssl_tls#62]
Hello,

I am trying to sniff live with this script with interface passed as an argument, but I get the error below:

    Traceback (most recent call last):
      File "sessionctx_sniffer.py", line 430, in <module>
        main((sys.argv[1],int(sys.argv[2])), iface=iface, pcap=pcap, keyfile=keyfile)
      File "sessionctx_sniffer.py", line 404, in main
        sniffer.sniff(target=target, keyfile=keyfile, iface=iface)
      File "sessionctx_sniffer.py", line 298, in sniff
        sniff(filter="host %s and tcp port %d"%(target[0],target[1]),prn=reassemble,store=0,timeout=None)
      File "/home/user/.local/lib/python2.7/site-packages/scapy/sendrecv.py", line 595, in sniff
        r = prn(p)
      File "sessionctx_sniffer.py", line 219, in reassemble
        decrypted = self.process_ssl(p)
      File "sessionctx_sniffer.py", line 179, in process_ssl
        session.insert(p_ssl) 
      File "/home/user/.local/lib/python2.7/site-packages/scapy/layers/ssl_tls_crypto.py", line 344, in insert
        self._process(p)    # fill structs
      File "/home/user/.local/lib/python2.7/site-packages/scapy/layers/ssl_tls_crypto.py", line 452, in _process
        explicit_iv)
      File "/home/user/.local/lib/python2.7/site-packages/scapy/layers/ssl_tls_crypto.py", line 823, in __init__
        raise RuntimeError("Cipher 0x%04x not supported" % cipher_suite)
    TypeError: %x format: a number is required, not NoneType

Any suggestions??

**Comment by tintinweb** [comment]
looks like it never saw a `TLSServerHello` and subsequently could not extract the negotiated ciphersuite `self.params.negotiated.ciphersuite==None` and then it failed in the `TLSSecurityParameters.__init__` due to the ciphersuite being `None`. 

Can you reproduce and provide a minmal testcase pcap? I'd like to investigate why it never processed the `TLSServerHello` which can have multiple causes.

**Comment by gunvant3** [comment]
It seems to be working. I had to switch the imports. Just needed:

```
from scapy.layers.ssl_tls import *
import scapy.layers.ssl_tls_crypto as ssl_tls_crypto
```

without the` try `and `except`.

**Comment by gunvant3** [comment]
Thank you very much for your response though! :)

**Comment by tintinweb** [comment]
feel free to reopen that issue if you run into that same error again. (also try to `#> pip uninstall scapy-ssl_tls` and `python setup.py install` it from source if you've checked out the source anyway)
