### ISSUE TITLE
server_rsa.py crashes with IndexError

### ISSUE THREAD

**Issue by teeshop** [tintinweb/scapy-ssl_tls#94]
Hi,

when running
```
sudo python server_rsa.py
```
and connecting to it, I get the following error:
```
Traceback (most recent call last):
  File "server_rsa.py", line 32, in <module>
    version = r[TLSClientHello].version
  File "/usr/lib64/python2.7/site-packages/scapy/packet.py", line 817, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [TLSClientHello] not found
```

I'm using the following versions:
```
$ pip list | grep scapy
scapy (2.3.2)
scapy-ssl-tls (1.2.3.2)
```

Is there any quick fix for this problem?

Kind regards, Jan

**Comment by tintinweb** [comment]
Hi @teeshop,

Thanks for taking the time to file a bug report. I tried to reproduce your issue but was unsuccessful in doing so. 

What tls client/version are you using?
Please check if dissection works without problems by calling `r.show()` after `c_socket.recvall()`. If it is working and the TLSClientHello layer is shown but you still get an IndexError there might be an issue with mixed imports (TLSClientHello being imported from scapy_ssl_tls and scapy.layers.ssl_tls) confusing scapy.




    # pip list | grep scapy
    scapy (2.3.2)
    scapy-ssl-tls (1.2.3.2)

server:

    (.env) # python examples/server_rsa.py
    <TLSSessionCtx: id=139882148389520
             params.handshake.client=<TLSClientHello  version=TLS_1_2 gmt_unix_time=1622359539 random_bytes='\x18\x9d\xb9\xc6\x07\xa8\xe7X\xfc\xbe\x87"\xdfh8\x10\x93.\xc9\x90W\xab\x8f\xfd\x86\xbe\xdd7' session_id_length=0x0 session_id='' cipher_suites_length=0xaa cipher_suites=['ECDHE_RSA_WITH_AES_256_GCM_SHA384', 'ECDHE_ECDSA_WITH_AES_256_GCM_SHA384', 'ECDHE_RSA_WITH_AES_256_CBC_SHA384', 'ECDHE_ECDSA_WITH_AES_256_CBC_SHA384', 'ECDHE_RSA_WITH_AES_256_CBC_SHA', 'ECDHE_ECDSA_WITH_AES_256_CBC_SHA', 'DH_DSS_WITH_AES_256_GCM_SHA384', 'DHE_DSS_WITH_AES_256_GCM_SHA384', 'DH_RSA_WITH_AES_256_GCM_SHA384', 'DHE_RSA_WITH_AES_256_GCM_SHA384', 'DHE_RSA_WITH_AES_256_CBC_SHA256', 'DHE_DSS_WITH_AES_256_CBC_SHA256', 'DH_RSA_WITH_AES_256_CBC_SHA256', 'DH_DSS_WITH_AES_256_CBC_SHA256', 'DHE_RSA_WITH_AES_256_CBC_SHA', 'DHE_DSS_WITH_AES_256_CBC_SHA', 'DH_RSA_WITH_AES_256_CBC_SHA', 'DH_DSS_WITH_AES_256_CBC_SHA', 'DHE_RSA_WITH_CAMELLIA_256_CBC_SHA', 'DHE_DSS_WITH_CAMELLIA_256_CBC_SHA', 'DH_RSA_WITH_CAMELLIA_256_CBC_SHA', 'DH_DSS_WITH_CAMELLIA_256_CBC_SHA', 'ECDH_RSA_WITH_AES_256_GCM_SHA384', 'ECDH_ECDSA_WITH_AES_256_GCM_SHA384', 'ECDH_RSA_WITH_AES_256_CBC_SHA384', 'ECDH_ECDSA_WITH_AES_256_CBC_SHA384', 'ECDH_RSA_WITH_AES_256_CBC_SHA', 'ECDH_ECDSA_WITH_AES_256_CBC_SHA', 'RSA_WITH_AES_256_GCM_SHA384', 'RSA_WITH_AES_256_CBC_SHA256', 'RSA_WITH_AES_256_CBC_SHA', 'RSA_WITH_CAMELLIA_256_CBC_SHA', 'ECDHE_RSA_WITH_AES_128_GCM_SHA256', 'ECDHE_ECDSA_WITH_AES_128_GCM_SHA256', 'ECDHE_RSA_WITH_AES_128_CBC_SHA256', 'ECDHE_ECDSA_WITH_AES_128_CBC_SHA256', 'ECDHE_RSA_WITH_AES_128_CBC_SHA', 'ECDHE_ECDSA_WITH_AES_128_CBC_SHA', 'DH_DSS_WITH_AES_128_GCM_SHA256', 'DHE_DSS_WITH_AES_128_GCM_SHA256', 'DH_RSA_WITH_AES_128_GCM_SHA256', 'DHE_RSA_WITH_AES_128_GCM_SHA256', 'DHE_RSA_WITH_AES_128_CBC_SHA256', 'DHE_DSS_WITH_AES_128_CBC_SHA256', 'DH_RSA_WITH_AES_128_CBC_SHA256', 'DH_DSS_WITH_AES_128_CBC_SHA256', 'DHE_RSA_WITH_AES_128_CBC_SHA', 'DHE_DSS_WITH_AES_128_CBC_SHA', 'DH_RSA_WITH_AES_128_CBC_SHA', 'DH_DSS_WITH_AES_128_CBC_SHA', 'DHE_RSA_WITH_SEED_CBC_SHA', 'DHE_DSS_WITH_SEED_CBC_SHA', 'DH_RSA_WITH_SEED_CBC_SHA', 'DH_DSS_WITH_SEED_CBC_SHA', 'DHE_RSA_WITH_CAMELLIA_128_CBC_SHA', 'DHE_DSS_WITH_CAMELLIA_128_CBC_SHA', 'DH_RSA_WITH_CAMELLIA_128_CBC_SHA', 'DH_DSS_WITH_CAMELLIA_128_CBC_SHA', 'ECDH_RSA_WITH_AES_128_GCM_SHA256', 'ECDH_ECDSA_WITH_AES_128_GCM_SHA256', 'ECDH_RSA_WITH_AES_128_CBC_SHA256', 'ECDH_ECDSA_WITH_AES_128_CBC_SHA256', 'ECDH_RSA_WITH_AES_128_CBC_SHA', 'ECDH_ECDSA_WITH_AES_128_CBC_SHA', 'RSA_WITH_AES_128_GCM_SHA256', 'RSA_WITH_AES_128_CBC_SHA256', 'RSA_WITH_AES_128_CBC_SHA', 'RSA_WITH_SEED_CBC_SHA', 'RSA_WITH_CAMELLIA_128_CBC_SHA', 'ECDHE_RSA_WITH_RC4_128_SHA', 'ECDHE_ECDSA_WITH_RC4_128_SHA', 'ECDH_RSA_WITH_RC4_128_SHA', 'ECDH_ECDSA_WITH_RC4_128_SHA', 'RSA_WITH_RC4_128_SHA', 'RSA_WITH_RC4_128_MD5', 'ECDHE_RSA_WITH_3DES_EDE_CBC_SHA', 'ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA', 'DHE_RSA_WITH_3DES_EDE_CBC_SHA', 'DHE_DSS_WITH_3DES_EDE_CBC_SHA', 'DH_RSA_WITH_3DES_EDE_CBC_SHA', 'DH_DSS_WITH_3DES_EDE_CBC_SHA', 'ECDH_RSA_WITH_3DES_EDE_CBC_SHA', 'ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA', 'RSA_WITH_3DES_EDE_CBC_SHA', 'EMPTY_RENEGOTIATION_INFO_SCSV'] compression_methods_length=0x1 compression_methods=['NULL'] extensions_length=0x55 extensions=[<TLSExtension  type=ec_point_formats length=0x4 |<TLSExtECPointsFormat  length=0x3 ec_point_formats=['uncompressed', 'ansiX962_compressed_prime', 'ansiX962_compressed_char2'] |>>, <TLSExtension  type=supported_groups length=0x1c |<TLSExtEllipticCurves  length=0x1a elliptic_curves=['secp256r1', 'secp521r1', 'brainpoolP512r1', 'brainpoolP384r1', 'secp384r1', 'brainpoolP256r1', 'secp256k1', 'sect571r1', 'sect571k1', 'sect409k1', 'sect409r1', 'sect283k1', 'sect283r1'] |>>, <TLSExtension  type=SessionTicket_TLS length=0x0 |>, <TLSExtension  type=signature_algorithms length=0x20 |<TLSExtSignatureAndHashAlgorithm  length=0x1e algs=[<TLSSignatureHashAlgorithm  hash_alg=sha512 sig_alg=rsa |>, <TLSSignatureHashAlgorithm  hash_alg=sha512 sig_alg=dsa |>, <TLSSignatureHashAlgorithm  hash_alg=sha512 sig_alg=ecdsa |>, <TLSSignatureHashAlgorithm  hash_alg=sha384 sig_alg=rsa |>, <TLSSignatureHashAlgorithm  hash_alg=sha384 sig_alg=dsa |>, <TLSSignatureHashAlgorithm  hash_alg=sha384 sig_alg=ecdsa |>, <TLSSignatureHashAlgorithm  hash_alg=sha256 sig_alg=rsa |>, <TLSSignatureHashAlgorithm  hash_alg=sha256 sig_alg=dsa |>, <TLSSignatureHashAlgorithm  hash_alg=sha256 sig_alg=ecdsa |>, <TLSSignatureHashAlgorithm  hash_alg=sha224 sig_alg=rsa |>, <TLSSignatureHashAlgorithm  hash_alg=sha224 sig_alg=dsa |>, <TLSSignatureHashAlgorithm  hash_alg=sha224 sig_alg=ecdsa |>, <TLSSignatureHashAlgorithm  hash_alg=sha1 sig_alg=rsa |>, <TLSSignatureHashAlgorithm  hash_alg=sha1 sig_alg=dsa |>, <TLSSignatureHashAlgorithm  hash_alg=sha1 sig_alg=ecdsa |>] |>>, <TLSExtension  type=heartbeat length=0x1 |<TLSExtHeartbeat  mode=peer_allowed_to_send |>>] |>
             params.handshake.server=<TLSServerHello  version=TLS_1_2 gmt_unix_time=1489133673 random_bytes='n\x9f\n>\x95$\x83I\x1a\xea\x19d\xb6A0\x89j\xca\xe3Z(\n\xabuC\xc4\x89=' session_id_length=0x14 session_id='\x82\x18\x13\x1d}\x1e\xf2\x04\x0b\xbb\x0e\xf8&\xf8\x92\xfc\xbb\x8dTe' cipher_suite=RSA_WITH_AES_128_CBC_SHA compression_method=NULL |>
             params.negotiated.version=TLS_1_2
             params.negotiated.ciphersuite=RSA_WITH_AES_128_CBC_SHA
             params.negotiated.key_exchange=RSA
             params.negotiated.encryption=('AES', 16, 'CBC')
             params.negotiated.mac=SHA
             params.negotiated.compression=NULL
             crypto.client.enc=<Crypto.Cipher.AES.AESCipher instance at 0x7f38d9b91a70>
             crypto.client.dec=<Crypto.Cipher.AES.AESCipher instance at 0x7f38d9b91b48>
             crypto.server.enc=<Crypto.Cipher.AES.AESCipher instance at 0x7f38d9b91b90>
             crypto.server.dec=<Crypto.Cipher.AES.AESCipher instance at 0x7f38d9b91bd8>
             crypto.client.rsa.privkey=None
             crypto.client.rsa.pubkey=None
             crypto.server.rsa.privkey=<_RSAobj @0x7f38d9c45d40 n(2048),e,d,p,q,u,private>
             crypto.server.rsa.pubkey=<_RSAobj @0x7f38d9b8ad88 n(2048),e>
             crypto.client.dsa.privkey=None
             crypto.client.dsa.pubkey=None
             crypto.server.dsa.privkey=None
             crypto.server.dsa.pubkey=None
             crypto.client.dh.x=None
             crypto.client.dh.y_c=None
             crypto.server.dh.p=None
             crypto.server.dh.g=None
             crypto.server.dh.x=None
             crypto.server.dh.y_s=None
             crypto.client.ecdh.curve_name=None
             crypto.client.ecdh.priv=None
             crypto.client.ecdh.pub=None
             crypto.server.ecdh.curve_name=None
             crypto.server.ecdh.priv=None
             crypto.server.ecdh.pub=None
             crypto.session.encrypted_premaster_secret=')\xa2\xec\xde\x1c\xdc\xb9$\xda\xed\xd9+\xbb\x0f\xab\x18[\x13eCO+x\xf77\x14\xaff\x99\x14Q\xaa\xff\xd3)\x19\xf0\xf6\xd1\x1e0\xc2\x18\x81W\x18|9\xe0\xe7!~\x13\xcc\x03\xa2\x02\x14\xd9\x92JaJ{7\xec\xfb\xa7\x9amoV\x96\xa4{\xac\x10\xc8\xcb\x0f\xa9n\x80\x7fD.\xac\xe4+M9\xfb\x04\xc1"(\xe8\xaf\x01\xbc\x15\x0e\xfe\xb3\x16\r)\x14\xbc\x85<\x1e%\xc6s\xb93\x8a\x82\xea\xa4\x93\x98\xf6\xbd\xaf\x86\xe3C\x02\xca7\xad\xec\xfc\xd8h?[\x00z\x88\xbb7\xb2\x07\xba\x8e\xa9)iVN\xa7\xe1\xcc\xe4\x1b\x08\xb6vNn\xfe\xc8b\xae\x1f\xc35\x88\xbc\x98\xd8\xd8\xfdB\x03t$\xe8\xce\x97\xf8\xb6\xe5\x87E\xc5\xdb{\x1d\xb7\x8ew\xf8\xd8\xa5\xf6p\x8d\xe0R\xab\x18\x98\xcb\xe9\xc9\xce^\xc2\x1a\xa7\xb9A\x16\xaaV,\xc8\xcb`\x95R\xc8=\x8bb\xdc\xed\xc5\xeaK\xef\x8b\x0f\x06\xde*)\xf2t\xde\xd0\x02\xe2\xe27\xeaX\x8b\xb94\x9f\xdf'
             crypto.session.premaster_secret='\x03\x03\xe1\xea\xb1\x19\x816\xf3\xac\xf5\xec\xfaI\x9d\xed\xbe^\x88y\x82\xc4\xf5L]\xaaun\x97B\xe9\xe1\x93\x14Y#\xf6\xd1[\xb9\xc3\xa1\xfa\xc0\n!\xc6G'
             crypto.session.master_secret='\xab\x954*\x196E\xf4\xae~^\x02;X\x9c\x11\x89\x7f\xcfk?\xd7\x8a!\xd0p,7\xa8\xe1\xef\x06g\x85\x9f\xceZ\xae2\xd7\nj\xec-\xdd\xe3\xff7'
             crypto.session.randombytes.client='`\xb3=\xf3\x18\x9d\xb9\xc6\x07\xa8\xe7X\xfc\xbe\x87"\xdfh8\x10\x93.\xc9\x90W\xab\x8f\xfd\x86\xbe\xdd7'
             crypto.session.randombytes.server='X\xc2`in\x9f\n>\x95$\x83I\x1a\xea\x19d\xb6A0\x89j\xca\xe3Z(\n\xabuC\xc4\x89='
             crypto.session.key.client.mac='\x95`\x1e\xddYgG:H9\xb2\xf6\x13\x1a\x19\xca\xdb\xd5\xbax'
             crypto.session.key.client.encryption='Z\xe2KD\x17O\x8fL\x92\x816\xad\xb5\xe6\x81\xb4'
             crypto.session.key.cllient.iv='\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
             crypto.session.key.server.mac='su\x86\x8c\x13\xd7\xe3\x03:\xd3\xf1\xf1\xa4\xbd/\x9ah\x8d\xda;'
             crypto.session.key.server.encryption='\x18\xf2,\xa2B6\x99m\x01\xd5-\xfc\x91?\xfay'
             crypto.session.key.server.iv='\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
             crypto.session.key.length.mac=20
             crypto.session.key.length.encryption=16
             crypto.session.key.length.iv=16

client:

    # openssl  s_client -connect localhost:8443
    CONNECTED(00000003)
    ...
    subject=/C=US/ST=Some-State/L=Some-city/O=Some-company/OU=Some-OU/CN=some-server.some.where
    issuer=/C=US/ST=Some-State/L=Some-city/O=Some-company/OU=Some-OU/CN=some-server.some.where
    ---
    No client certificate CA names sent
    ---
    SSL handshake has read 1304 bytes and written 647 bytes
    ---
    New, TLSv1/SSLv3, Cipher is AES128-SHA
    Server public key is 2048 bit
    Secure Renegotiation IS NOT supported
    Compression: NONE
    Expansion: NONE
    No ALPN negotiated
    SSL-Session:
        Protocol  : TLSv1.2
        Cipher    : AES128-SHA
        Session-ID: 8218131D7D1EF2040BBB0EF826F892FCBB8D5465
        Session-ID-ctx:
        Master-Key: AB95342A193645F4AE7E5E023B589C11897FCF6B3FD78A21D0702C37A8E1EF0667859FCE5AAE32D70A6AEC2DDDE3FF37
        Key-Arg   : None
        PSK identity: None
        PSK identity hint: None
        SRP username: None
        Start Time: 1489133718
        Timeout   : 300 (sec)
        Verify return code: 18 (self signed certificate)
    ---
    It works!
    closed

**Comment by tintinweb** [comment]
closing due to inactivity. feel free to reopen if the problem persists.

**Comment by alexmgr** [comment]
Just for the record, I've seen this behavior before, when the client side is buggy and does not allow empty reads on the socket.

In that scenario, you need to use a plain `recv` with a large enough buffer instead of `recvall`, and hope that `read` returns the whole thing in one go. Can also hack patch `recvall` like this:
```
    def recvall(self, size=8192 * 4, timeout=0.5):
        resp = []
        prev_timeout = self._s.gettimeout()
        self._s.settimeout(timeout)
        try:
            data = self._s.recv(size)
            resp.append(data)
        except socket.timeout:
            break
        self._s.settimeout(prev_timeout)
        records = TLS("".join(resp), ctx=self.tls_ctx, _origin=self._get_pkt_origin('in'))
        return records
```
